name: Recall CI/CD Pipeline

on:
  push:
    branches:
      - develop-05
      - main
# env:
#   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#   REPO_NAME: ${{ github.event.repository.name }}
#   REPO_OWNER: ${{ github.event.repository.owner.login }}
#   GITHUB_API_URL: https://api.github.com
#   GITHUB_RUN_ID: ${{ github.run_id }}
#   GITHUB_RUN_NUMBER: ${{ github.run_number }}
#   GITHUB_RUN_URL: ${{ github.run_url }}
#   GITHUB_WORKFLOW: ${{ github.workflow }}
#   GITHUB_SHA: ${{ github.sha }}


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
    
          - name: Setup .NET
            uses: actions/setup-dotnet@v3
            with:
              dotnet-version: 8.x      

          - name: restote solution
            run: dotnet restore
         
          - name: Build project
            run: dotnet build --configuration Release

          - name: publish project
            run:   dotnet publish  --configuration Release --output ./publish
    
          - name: Run tests
            run: dotnet test --configuration Release --no-build --verbosity normal

          - name: Build Docker image
            run: |
              docker build -t recall:latest .
    


    
    # deploy:
    #     runs-on: ubuntu-latest
    #     needs: build
    #     steps:
    #       - name: Checkout code
    #         uses: actions/checkout@v2
    
    #       - name: Deploy to production
    #         run: |
    #           echo "Deploying to production..."
    #         # Add your deployment commands here
    